apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: elastic-storage
    fsType: ext4
