steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/hserver', '-t', 'asia.gcr.io/$PROJECT_ID/hserver:$COMMIT_SHA', '-f', './Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "asia.gcr.io/$PROJECT_ID/hserver"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/hserver-stage'
  - 'hserver-stage=asia.gcr.io/$PROJECT_ID/hserver:$COMMIT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hypo'

#kubectl create configmap nginx-proxy-conf --from-file=proxy.conf
